services:
  counter:
    build:
      context: .
      dockerfile: cmd/counter/Dockerfile
  redirect:
    build:
      context: .
      dockerfile: cmd/redirect/Dockerfile
  shortener:
    build:
      context: .
      dockerfile: cmd/shortener/Dockerfile
